/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Karol Miklas (https://sketchfab.com/karolmiklas)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/free-1972-datsun-240k-gt-b2303a552b444e5b8637fdf5169b41cb
title: (FREE) 1972 Datsun 240k GT
*/

import {  MeshPortalMaterial, MeshWobbleMaterial, useFBX, useTexture } from '@react-three/drei'
import { useThree } from '@react-three/fiber'
import { Children, useRef } from 'react';


export function Model({ color }) {
  const fbxModel = useFBX('/HR_jill_v02.fbx');
  const scene = useThree().scene
  const groupRef = useRef()
  console.log("🚀 ~ Model ~ groupRef:", groupRef)
  const textures = useTexture({
    displacementMap: './textures/ZIMMER/DISP_4K.jpg',
    normalMap: './textures/TX_cushion_NM_01.png',
    map: './textures/ZIMMER/COL_4K.jpg',
    roughnessMap: './textures/ZIMMER/ROUGH_4K.jpg',
    diffusionMap: './textures/ZIMMER/DIFF_4K.jpg',
    aoMap: './textures/ZIMMER/AO_4K.jpg',
    metalnessMap: './textures/ZIMMER/METAL_4K.jpg',
  });
  fbxModel.traverse((child) => {
    if (child.isMesh) {
      child.material.normalMap = textures.normalMap;
      child.material.displacementMap = textures.displacementMap;
      child.material.map = textures.map;
      child.material.roughnessMap = textures.roughnessMap;
      child.material.diffusionMap = textures.diffusionMap;
      child.material.aoMap = textures.aoMap;
      child.material.metalnessMap = textures.metalnessMap;
    }
  });

  return (
    <group ref={groupRef} dispose={null} scale={0.01}>
      <primitive object={fbxModel} />
    </group>
  );
}

useFBX.preload('/HR.fbx')
